apiVersion: v1
kind: Secret
metadata:
  name: mysql-database-app-secret
  namespace: database
  labels:
    app: mysql
    enviorment: database
type: Opaque
data:
  user: admin     #username 
  password: YWRtaW4xMjMK   #admin123
