apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv-vol
  namespace: database
  lables: 
    app: mysql
    enviroment: database
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/sqldata
    server: 172.31.6.95

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc-uses
  namespace: database
  lables: 
    app: mysql
    enviroment: database
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
